application: shakespy
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: controller.application

includes:
- mapreduce/include.yaml

libraries:
- name: jinja2
  version: "2.6"
